from setuptools import setup, find_packages
import sys

setup(
    name="the_edge_agent",
    version="0.4.1",
    author="Fabricio Ceolin",
    author_email="fabceolin@gmail.com",
    description="A lightweight, single-app state graph library inspired by LangGraph, to run on edge computing",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/fabceolin/the_edge_agent",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
    install_requires=[
        "networkx==3.3",
        "pygraphviz==1.13",
        "pyyaml>=6.0",
        "jmespath>=1.0.0",
        "jsonschema>=4.20.0",
    ],
    extras_require={
        "dev": ["pytest", "coverage", "hypothesis", "parameterized==0.9.0"],
        "rag": ["openai>=1.13.3", "numpy>=2.1.0"],
        "rag-chroma": ["openai>=1.13.3", "numpy>=2.1.0", "chromadb>=0.4.0"],
        "llm": ["openai>=1.13.3"],
        "web": ["requests>=2.32.5"],
        "code": ["RestrictedPython>=8.0"],
        "graph": ["pycozo[embedded]>=0.7.0"],
        "tools-crewai": ["crewai>=1.6.0", "crewai-tools>=0.38.0"],
        "tools-mcp": ["mcp>=1.23.0"],
        "tools-langchain": ["langchain>=1.1.0", "langchain-community>=0.4.0"],
        "tools": [
            "crewai>=1.6.0",
            "crewai-tools>=0.38.0",
            "mcp>=1.23.0",
            "langchain>=1.1.0",
            "langchain-community>=0.4.0",
        ],
        "all": [
            "openai>=1.13.3",
            "numpy>=2.1.0",
            "chromadb>=0.4.0",
            "requests>=2.32.5",
            "RestrictedPython>=8.0",
            "pycozo[embedded]>=0.7.0",
        ],
    },
)
